
<a id='fundamental-types'></a>
<div id="qe-notebook-header" style="text-align:right;">
        <a href="https://quantecon.org/" title="quantecon.org">
                <img style="width:250px;display:inline;" src="https://assets.quantecon.org/img/qe-menubar-logo.svg" alt="QuantEcon">
        </a>
</div>

# Arrays, Tuples, Ranges, e Outros Tipos Fundamentais

## Conteúdo

- [Arrays, Tuples, Ranges, e Outros Tipos Fundamentais](#Arrays,-Tuples,-Ranges,-e-Outros-Tipos-Fundamentais)  
  - [Resumo](#Resumo)  
  - [Noções Básicas de Matrizes](#Noções-Básicas-de-Matrizes)  
  - [Operações em Matrizes](#Operações-em-Matrizes)  
  - [Ranges](#Ranges)  
  - [Tuples e Tuples Nomeados](#Tuples-e-Tuples-Nomeados)  
  - [Nothing, Missing, e Unions](#Nothing,-Missing,-e-Unions)  
  - [Exercícos](#Exercícios)  
  - [Soluções](#Soluções)  

> *Devidamente traduzido, revisado e adaptado do [QuantEcon](https://quantecon.org/) pelos bolsistas CNPq, Pedro Luiz H. Furtado e Jonas Aragão M. Corpes, sob supervisão do Prof. Christiano Penna, do CAEN/UFC.*

>> “Sejamos claros: o trabalho da ciência não tem nada a ver com consenso.
> O consenso é o negócio da política. A ciência, pelo contrário, exige apenas
> um pesquisador que esteja certo, o que significa que ele ou ela tem
> resultados verificáveis por referência ao mundo real. Na ciência
> o consenso é irrelevante. O que é relevante são os resultados reproduzíveis.” – Michael Crichton

## Resumo

Em Julia, matrizes e tuplas são o tipo de dados mais importante para trabalhar com dados numéricos.

Nesta aula, damos mais detalhes sobre:

- criar e manipular matrizes no Julia.  
- operações fundamentais de processamento de matriz.
- álgebra matricial básica.  
- tuples e tuples nomeados .
- ranges.  
- nothing, missing, e unions.

### Configuração

In [1]:
using InstantiateFromURL
github_project("QuantEcon/quantecon-notebooks-julia", version = "0.5.0")
# github_project("QuantEcon/quantecon-notebooks-julia", version = "0.5.0", instantiate = true) # uncomment to force package installation

In [2]:
using LinearAlgebra, Statistics

## Noções Básicas de Matrizes

([Veja a documetação de matrizes multi-dimensinais](https://docs.julialang.org/en/v1/manual/arrays/))

Como é um dos tipos mais importantes, começaremos com matrizes.

Mais tarde, veremos como as matrizes (e todos os outros tipos em Julia) são tratadas de maneira genérica e extensível.

### Forma e Dimensão

Já vimos algumas matrizes em Julia em ação.

In [3]:
a = [10, 20, 30]

3-element Array{Int64,1}:
 10
 20
 30

In [4]:
a = [1.0, 2.0, 3.0]

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

A saída nos diz que as matrizes são dos tipos `Array{Int64,1}` e `Array{Float64,1}` respectivamente.

Aqui `Int64` e `Float64` estão os tipos para os elementos inferidos pelo compilador.

Falaremos mais sobre tipos depois.

O `1` em `Array{Int64,1}` e `Array{Any,1}` indica que a matriz é unidimensional (ou seja, um `vetor`).

Esse é o padrão para muitas funções Julia que criam matrizes.

In [5]:
typeof(randn(100))

Array{Float64,1}

Em Julia, os vetores unidimensionais são melhor interpretados como vetores de coluna, que veremos quando fizermos transposições.

Podemos verificar as dimensões de `a` usando as funções `size()`e `ndims()`. 

In [6]:
ndims(a)

1

In [7]:
size(a)

(3,)

A sintaxe `(3,)` exibe uma tupla contendo um elemento - o tamanho ao longo da única dimensão que existe.

#### Array vs Vetor vs Matriz

Em Julia, `Vetor` e `Matriz` são apenas para matrizes unidimensionais e bidimensionais, respectivamente.

In [8]:
Array{Int64, 1} == Vector{Int64}
Array{Int64, 2} == Matrix{Int64}

true

A construção do vetor com `,` é então interpretada como um vetor de coluna.

Para ver isso, podemos criar um vetor de coluna e vetor de linha mais diretamente.

In [9]:
[1, 2, 3] == [1; 2; 3]  # ambos vetores colunas

true

In [10]:
[1 2 3]  # um vetor de linha é bidimensional

1×3 Array{Int64,2}:
 1  2  3

Como vimos, em Julia, temos ambos:

- matrizes unidimensionais (ou seja, matrizes planas).
- matrizes de tamanho `(1, n)`ou `(n, 1)`que representam vetores de linha e coluna, respectivamente.

Por que precisamos dos dois?

Por um lado, a dimensão é importante para a álgebra matricial.

 - Multiplicar por um vetor de linha é diferente de multiplicar por um vetor de coluna.
 
Por outro lado, usamos matrizes em muitas configurações que não envolvem álgebra matricial.

Nesses casos, não nos importamos com a distinção entre vetores de linha e coluna.

É por isso que muitas funções Julia retornam matrizes simples por padrão.



<a id='creating-arrays'></a>

### Criando Matrizes (arrays)

#### Funções que Criam Matrizes

Já vimos algumas funções para criar um vetor preenchido com `0.0`

In [11]:
zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

Isso generaliza para matrizes e matrizes dimensionais mais altas.

In [12]:
zeros(2, 2)

2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

Para retornar uma matriz preenchida com um único valor, use `fill`.

In [13]:
fill(5.0, 2, 2)

2×2 Array{Float64,2}:
 5.0  5.0
 5.0  5.0

Por fim, você pode criar uma matriz vazia usando o `Array()` construtor.

In [14]:
x = Array{Float64}(undef, 2, 2)

2×2 Array{Float64,2}:
 6.94202e-310  6.94202e-310
 6.94202e-310  6.94202e-310

Os valores retornados que você vê aqui são apenas valores de resíduo.

(o conteúdo existente dos slots de memória alocados é interpretado como flutuadores de 64 bits).

Se você precisar de mais controle sobre os tipos, preencha com um ponto não flutuante.

In [15]:
fill(0, 2, 2)  # completa com 0, e não 0.0

2×2 Array{Int64,2}:
 0  0
 0  0

Ou preenche com um tipo booleano.

In [16]:
fill(false, 2, 2)  # produz uma matriz booleana

2×2 Array{Bool,2}:
 0  0
 0  0

#### Criando Matrizes a partir de Matrizes Existentes 

Na maioria das vezes, evitaremos especificar diretamente os tipos de matrizes e deixar o compilador deduzir os tipos ideais por si só.

As razões para isso, discutidas em mais detalhes [nesta aula](https://lectures.quantecon.org/more_julia/generic_programming.html), para garantir clareza e generalidade.

Um lugar em que isso pode ser inconveniente é quando precisamos criar uma matriz com base em uma matriz existente.

Primeiro, observe que a atribuição em Julia vincula um nome a um valor, mas não faz uma cópia desse tipo.

In [17]:
x = [1, 2, 3]
y = x
y[1] = 2
x

3-element Array{Int64,1}:
 2
 2
 3

No exemplo acima, `y = x` basta criar uma nova ligação nomeada chamada `y` que se refere ao que for vinculado a `x` atualmente.

Para copiar os dados, você precisa ser mais explícito.

In [18]:
x = [1, 2, 3]
y = copy(x)
y[1] = 2
x

3-element Array{Int64,1}:
 1
 2
 3

No entanto, em vez de fazer uma cópia `x`, convém ter uma matriz de tamanho semelhante.

In [19]:
x = [1, 2, 3]
y = similar(x)
y

3-element Array{Int64,1}:
 140507866246800
 140507908265520
 140507866246832

Também podemos usar `similar` para pré-alocar um vetor com um tamanho diferente, mas com a mesma forma.

In [20]:
x = [1, 2, 3]
y = similar(x, 4)  # faz um vetor de comprimento 4 

4-element Array{Int64,1}:
 140508183850240
 140508223998048
 140508178226880
 140508178227072

O que generaliza para dimensões mais altas.

In [21]:
x = [1, 2, 3]
y = similar(x, 2, 2)  # faz uma matriz 2x2

2×2 Array{Int64,2}:
 140507867184624  140507867184688
 140507867184656  140507867184720

#### Definições de Matriz Manual

Como vimos, você pode criar matrizes unidimensionais a partir de dados especificados manualmente, como:

In [22]:
a = [10, 20, 30, 40]

4-element Array{Int64,1}:
 10
 20
 30
 40

Em duas dimensões, podemos proceder da seguinte forma:

In [23]:
a = [10 20 30 40]  # two dimensional, shape is 1 x n

1×4 Array{Int64,2}:
 10  20  30  40

In [24]:
ndims(a)

2

In [25]:
a = [10 20; 30 40]  # 2 x 2

2×2 Array{Int64,2}:
 10  20
 30  40

Você pode assumir que `a = [10; 20; 30; 40]` cria um vetor de coluna bidimensional, mas esse não é o caso:

In [26]:
a = [10; 20; 30; 40]

4-element Array{Int64,1}:
 10
 20
 30
 40

In [27]:
ndims(a)

1

Em vez disso, transponha a matriz (ou adjunta, se complexa).

In [28]:
a = [10 20 30 40]'

4×1 Adjoint{Int64,Array{Int64,2}}:
 10
 20
 30
 40

In [29]:
ndims(a)

2

### Indexação de Matrizes

Já vimos o básico da indexação de matrizes.

In [30]:
a = [10 20 30 40]
a[end-1]

30

In [31]:
a[1:3]

3-element Array{Int64,1}:
 10
 20
 30

Para matrizes 2D, a sintaxe do índice é simples.

In [32]:
a = randn(2, 2)
a[1, 1]

0.8511701328872764

In [33]:
a[1, :]  # primeira linha

2-element Array{Float64,1}:
  0.8511701328872764
 -0.6109318407103239

In [34]:
a[:, 1]  # primeira coluna

2-element Array{Float64,1}:
 0.8511701328872764 
 0.32429326573093237

Booleanos podem ser usados para extrair elementos.

In [35]:
a = randn(2, 2)

2×2 Array{Float64,2}:
 -1.32581   -0.988361
 -0.123497   1.06086 

In [36]:
b = [true false; false true]

2×2 Array{Bool,2}:
 1  0
 0  1

In [37]:
a[b]

2-element Array{Float64,1}:
 -1.3258053746923157
  1.0608645079380372

Isso é útil para extração condicional, como veremos abaixo

Uma parte: alguns ou todos os elementos de uma matriz podem ser configurados iguais a um número usando a notação de fatia.

In [38]:
a = zeros(4)

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [39]:
a[2:end] .= 42

3-element view(::Array{Float64,1}, 2:4) with eltype Float64:
 42.0
 42.0
 42.0

In [40]:
a

4-element Array{Float64,1}:
  0.0
 42.0
 42.0
 42.0

### Visualizações e Fatias

Usando a notação `:` fornece uma fatia de uma matriz, copiando a sub-matriz para uma nova matriz com um tipo semelhante.

In [41]:
a = [1 2; 3 4]
b = a[:, 2]
@show b
a[:, 2] = [4, 5] # modifica a
@show a
@show b;

b = [2, 4]
a = [1 4; 3 5]
b = [2, 4]


Um **view** por outro lado não copia o valor.

In [42]:
a = [1 2; 3 4]
@views b = a[:, 2]
@show b
a[:, 2] = [4, 5]
@show a
@show b;

b = [2, 4]
a = [1 4; 3 5]
b = [4, 5]


Observe que a única diferença é a macro `@views`, que substituirá as fatias pelas exibições na expressão.

Uma alternativa é chamar diretamente a função `view` - embora geralmente seja desencorajada, pois está a um passo da matemática.

In [43]:
@views b = a[:, 2]
view(a, :, 2) == b

true

Como na maioria dos programas em Julia, é melhor evitar assumir prematuramente que isso `@views` terá um impacto significativo no desempenho e, acima de tudo, na clareza do código de estresse.

Outra lição importante `@views`é que eles não são matrizes densas e normais.

In [44]:
a = [1 2; 3 4]
b_slice = a[:, 2]
@show typeof(b_slice)
@show typeof(a)
@views b = a[:, 2]
@show typeof(b);

typeof(b_slice) = Array{Int64,1}
typeof(a) = Array{Int64,2}
typeof(b) = SubArray{Int64,1,Array{Int64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}


O tipo de `b` é um bom exemplo de como os tipos não são o que parecem.

Similarmente.

In [45]:
a = [1 2; 3 4]
b = a'   # transposta
typeof(b)

Adjoint{Int64,Array{Int64,2}}

Copia em uma matriz densa.

In [46]:
a = [1 2; 3 4]
b = a' # transposta
c = Matrix(b)  # converte em matriz
d = collect(b) # também `collect` funciona em qualquer iterável 
c == d

true

### Matrizes Especiais

Como vimos `transpose`, às vezes os tipos que se parecem com matrizes não são armazenados como uma matriz densa

Como exemplo, considere criar uma matriz diagonal.

In [47]:
d = [1.0, 2.0]
a = Diagonal(d)

2×2 Diagonal{Float64,Array{Float64,1}}:
 1.0   ⋅ 
  ⋅   2.0

Como você pode ver, o tipo é `2×2 Diagonal{Float64,Array{Float64,1}}`, que não é uma matriz bidimensional.

As razões para isso são tanto a eficiência no armazenamento, quanto a eficiência nas operações aritméticas e matriciais.

Em todos os aspectos importantes, tipos de matrizes como Diagonal são tão "matrizes" quanto as matrizes densas que usamos (veja a [aula de introdução de tipos](https://lectures.quantecon.org/introduction_to_types.html) mais)

In [48]:
@show 2a
b = rand(2,2)
@show b * a;

2a = [2.0 0.0; 0.0 4.0]
b * a = [0.5440352543513847 0.2659475642337137; 0.5923155605866313 0.19106495963840775]


Outro exemplo está na construção de uma matriz de identidade, onde uma implementação ingênua é:

In [49]:
b = [1.0 2.0; 3.0 4.0]
b - Diagonal([1.0, 1.0])  # estilo ruim, ineficiênte código

2×2 Array{Float64,2}:
 0.0  2.0
 3.0  3.0

Considerando que você deveria usar:

In [50]:
b = [1.0 2.0; 3.0 4.0]
b - I  # estilo bom, e observe a falta de dimensões de I

2×2 Array{Float64,2}:
 0.0  2.0
 3.0  3.0

Embora a implementação de `I` seja um pouco abstrata para abordar neste momento, uma dica é:

In [51]:
typeof(I)

UniformScaling{Bool}

Este é um tipo `UniformScaling` e não uma matriz de identidade, tornando-o muito mais poderoso e geral.

### Matrizes de atribuição e passagem 

Como discutido acima, em Julia, o lado esquerdo de uma atribuição é uma "ligação" ou um rótulo para um valor.

In [52]:
x = [1 2 3]
y = x  # nome `y` se liga a qualquer valor` x` vinculado 

1×3 Array{Int64,2}:
 1  2  3

 consequência disso é que você pode vincular novamente esse nome.

In [53]:
x = [1 2 3]
y = x        # nome `y` se liga a qualquer` x` vinculado 
z = [2 3 4]
y = z        # apenas altera a ligação do nome, não o valor! 
@show (x, y, z);

(x, y, z) = ([1 2 3], [2 3 4], [2 3 4])


O que isto significa é que, se `a` é um array e partimos `b = a` em seguida, `a` e `b` apontam para exatamente os mesmos dados.

Acima, suponha que você pretendia alterar o valor de `x` para os valores de `y`, você precisa atribuir os valores em vez do nome.

In [54]:
x = [1 2 3]
y = x       # nome `y` se liga a qualquer` x` vinculado 
z = [2 3 4]
y .= z      # agora despacha a atribuição de cada elemento
@show (x, y, z);

(x, y, z) = ([2 3 4], [2 3 4], [2 3 4])


Como alternativa, você poderia ter usado `y[:] = z`

Isso se aplica também às funções no local.

Primeiro, defina uma função simples para um mapa linear.

In [55]:
function f(x)
    return [1 2; 3 4] * x  # matriz * vetor coluna
end

val = [1, 2]
f(val)

2-element Array{Int64,1}:
  5
 11

Em geral, essas funções “out-place” são preferidas às funções “in-place”, que modificam os argumentos.

In [56]:
function f(x)
    return [1 2; 3 4] * x # matriz * vetor coluna
end

val = [1, 2]
y = similar(val)

function f!(out, x)
    out .= [1 2; 3 4] * x
end

f!(y, val)
y

2-element Array{Int64,1}:
  5
 11

Isso demonstra uma convenção importante em Julia: funções que modificam qualquer um dos argumentos têm o nome terminado em `!` (por exemplo `push!`).

Também podemos ver um erro comum, onde, em vez de modificar os argumentos, a ligação do nome é trocada.

In [57]:
function f(x)
    return [1 2; 3 4] * x  # matriz * vetor coluna
end

val = [1, 2]
y = similar(val)

function f!(out, x)
    out = [1 2; 3 4] * x   # ERRO! deve ser .= ou [:]
end
f!(y, val)
y

2-element Array{Int64,1}:
 140508178228992
 140508178228992

A frequência de cometer esse erro é um dos motivos para evitar funções no local, a menos que seja provado ser necessário comparando.

### In-place e Tipos Imutáveis

Observe que os escalares são sempre imutáveis, de modo que:

In [58]:
y = [1 2]
y .-= 2    # y .= y .- 2, sem problema

x = 5
# x .-= 2  # falha!
x = x - 2  # diferença sutil - cria um novo valor e religa a variável

3

Em particular, não há como passar imutáveis para uma função e modificá-la:


In [59]:
x = 2

function f(x)
    x = 3     # ERRO! não modifica x, cria um novo valor! 
end

f(x)          # não pode modificar imutáveis no lugar 
@show x;

x = 2


Isso também é válido para outros tipos imutáveis, como tuplas, bem como para alguns tipos de vetores.

In [60]:
using StaticArrays
xdynamic = [1, 2]
xstatic = @SVector [1, 2]  # transforma em um vetor estático altamente otimizado

f(x) = 2x
@show f(xdynamic)
@show f(xstatic)

# inplace versão
function g(x)
    x .= 2x
    return "Success!"
end
@show xdynamic
@show g(xdynamic)
@show xdynamic;

# g(xstatic) # falha, vetores estáticos são imutáveis

f(xdynamic) = [2, 4]
f(xstatic) = [2, 4]
xdynamic = [1, 2]
g(xdynamic) = "Success!"
xdynamic = [2, 4]


## Operações em Matrizes

### Métodos de Matriz

Julia fornece funções padrão para atuar em matrizes, algumas das quais já vimos.

In [61]:
a = [-1, 0, 1]

@show length(a)
@show sum(a)
@show mean(a)
@show std(a)      # desvio padrão
@show var(a)      # variância
@show maximum(a)
@show minimum(a)
@show extrema(a)  # (mínimo(a), máximo(a))

length(a) = 3
sum(a) = 0
mean(a) = 0.0
std(a) = 1.0
var(a) = 1.0
maximum(a) = 1
minimum(a) = -1
extrema(a) = (-1, 1)


(-1, 1)

Para classificar uma matriz.

In [62]:
b = sort(a, rev = true)  # retorna nova matriz, original não modificado

3-element Array{Int64,1}:
  1
  0
 -1

In [63]:
b = sort!(a, rev = true)  # retorna a *matriz  original* modificada

3-element Array{Int64,1}:
  1
  0
 -1

In [64]:
b == a  # testa se tem os mesmos valores

true

In [65]:
b === a  # testa se as matrizes são idênticas (isto é, compartilham a mesma memória)

true

### Álgebra Matricial

Para matrizes bidimensionais, `*` significa multiplicação de matrizes.

In [66]:
a = ones(1, 2)

1×2 Array{Float64,2}:
 1.0  1.0

In [67]:
b = ones(2, 2)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [68]:
a * b

1×2 Array{Float64,2}:
 2.0  2.0

In [69]:
b * a'

2×1 Array{Float64,2}:
 2.0
 2.0

Para resolver o sistema linear $ A X = B $ para $ X $ use `A \ B`

In [70]:
A = [1 2; 2 3]

2×2 Array{Int64,2}:
 1  2
 2  3

In [71]:
B = ones(2, 2)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [72]:
A \ B

2×2 Array{Float64,2}:
 -1.0  -1.0
  1.0   1.0

In [73]:
inv(A) * B

2×2 Array{Float64,2}:
 -1.0  -1.0
  1.0   1.0

Embora as duas últimas operações apresentem o mesmo resultado, a primeira é numericamente mais estável e deve ser preferida na maioria dos casos

Multiplicando dois vetores **uni**dimensionais dá um erro - que é razoável, já que o significado é ambíguo

Mais precisamente, o erro é que não existe uma implementação `*`para vetores bidimensionais

A saída explica isso e lista alguns outros métodos `*`que Julia acha que estão próximos do que queremos

In [74]:
ones(2) * ones(2)

MethodError: MethodError: no method matching *(::Array{Float64,1}, ::Array{Float64,1})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:529
  *(!Matched::Adjoint{#s627,#s626} where #s626<:Union{DenseArray{T,2}, Base.ReinterpretArray{T,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{T,2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{T,2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}} where #s627, ::Union{DenseArray{S,1}, Base.ReinterpretArray{S,1,S1,A} where S1 where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{S,1,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{S,1,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}) where {T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64}, S} at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/LinearAlgebra/src/matmul.jl:106
  *(!Matched::Adjoint{#s627,#s626} where #s626<:LinearAlgebra.AbstractTriangular where #s627, ::AbstractArray{T,1} where T) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/LinearAlgebra/src/triangular.jl:1877
  ...

Se você deseja um produto interno nessa configuração, use `dot()` ou o unicode `\cdot<TAB>`

In [75]:
dot(ones(2), ones(2))

2.0

A multiplicação de matrizes usando vetores unidimensionais é um pouco inconsistente -
a pré-multiplicação pela matriz está OK, mas a pós-multiplicação gera um erro.

In [76]:
b = ones(2, 2)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [77]:
b * ones(2)

2-element Array{Float64,1}:
 2.0
 2.0

In [78]:
ones(2) * b

DimensionMismatch: DimensionMismatch("A has dimensions (2,1) but B has dimensions (2,2)")

### Operações Elementares

#### Operações Algébricas

Suponha que desejamos multiplicar cada elemento da matriz `A`pelo elemento correspondente da matriz `B`.

Nesse caso, precisamos substituir `*`(multiplicação de matrizes) por `.*`(multiplicação por elementos).

Por exemplo, compare:

In [79]:
ones(2, 2) * ones(2, 2)   # multiplicação de matrizes

2×2 Array{Float64,2}:
 2.0  2.0
 2.0  2.0

In [80]:
ones(2, 2) .* ones(2, 2)   # multiplicação elemento por elemento

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

Este é um princípio geral: `.x` significa aplicar operador `x` elementar.

In [81]:
A = -ones(2, 2)

2×2 Array{Float64,2}:
 -1.0  -1.0
 -1.0  -1.0

In [82]:
A.^2  # eleva todos os elementos ao quadrado

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

No entanto, na prática, algumas operações são matematicamente válidas sem transmissão e, portanto, `.` podem ser omitidas.

In [83]:
ones(2, 2) + ones(2, 2)  # igual a  ones(2, 2) .+ ones(2, 2)

2×2 Array{Float64,2}:
 2.0  2.0
 2.0  2.0

A multiplicação escalar é semelhante.

In [84]:
A = ones(2, 2)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [85]:
2 * A  # mesmo como 2 .* A

2×2 Array{Float64,2}:
 2.0  2.0
 2.0  2.0

Na verdade, você pode omitir `*` tudo e apenas escrever `2A`.

Ao contrário do MATLAB e de outros idiomas, a adição escalar requer a `.+` transmissão correta.

In [86]:
x = [1, 2]
x .+ 1     # não x + 1
x .- 1     # não x - 1

2-element Array{Int64,1}:
 0
 1

#### Comparições Elementares 

As comparações elementares também usam a notação `.x`  de estilo.

In [87]:
a = [10, 20, 30]

3-element Array{Int64,1}:
 10
 20
 30

In [88]:
b = [-100, 0, 100]

3-element Array{Int64,1}:
 -100
    0
  100

In [89]:
b .> a

3-element BitArray{1}:
 0
 0
 1

In [90]:
a .== b

3-element BitArray{1}:
 0
 0
 0

Também podemos fazer comparações com escalares com sintaxe paralela.

In [91]:
b

3-element Array{Int64,1}:
 -100
    0
  100

In [92]:
b .> 1

3-element BitArray{1}:
 0
 0
 1

Isso é particularmente útil para extração condicional - extraindo os elementos de uma matriz que satisfazem uma condição.

In [93]:
a = randn(4)

4-element Array{Float64,1}:
 -0.3121756665292232
  0.4806007200510856
  0.3736604782200087
  0.8942833931647776

In [94]:
a .< 0

4-element BitArray{1}:
 1
 0
 0
 0

In [95]:
a[a .< 0]

1-element Array{Float64,1}:
 -0.3121756665292232

#### Mudando as Dimensões

A função principal para alterar as dimensões de uma matriz é `reshape()`

In [96]:
a = [10, 20, 30, 40]

4-element Array{Int64,1}:
 10
 20
 30
 40

In [97]:
b = reshape(a, 2, 2)

2×2 Array{Int64,2}:
 10  30
 20  40

In [98]:
b

2×2 Array{Int64,2}:
 10  30
 20  40

Observe que essa função retorna uma exibição na matriz existente.

Isso significa que alterar os dados na nova matriz modificará os dados na antiga.

In [99]:
b[1, 1] = 100  # continuando o exemplo anterior

100

In [100]:
b

2×2 Array{Int64,2}:
 100  30
  20  40

In [101]:
a

4-element Array{Int64,1}:
 100
  20
  30
  40

Para recolher uma matriz ao longo de uma dimensão, você pode usar `dropdims()`

In [102]:
a = [1 2 3 4]  # duas dimensões

1×4 Array{Int64,2}:
 1  2  3  4

In [103]:
dropdims(a, dims = 1)

4-element Array{Int64,1}:
 1
 2
 3
 4

O valor de retorno é uma matriz com a dimensão especificada "achatada".

### Funções de Transmissão

Julia fornece funções matemáticas padrão, como `log`, `exp`, `sin`, etc.

In [104]:
log(1.0)

0.0

Por padrão, essas funções agem de maneira *elementar* em matrizes.

In [105]:
log.(1:4)

4-element Array{Float64,1}:
 0.0               
 0.6931471805599453
 1.0986122886681098
 1.3862943611198906

Observe que podemos obter o mesmo resultado a partir de uma compreensão ou loop mais explícito.

In [106]:
[ log(x) for x in 1:4 ]

4-element Array{Float64,1}:
 0.0               
 0.6931471805599453
 1.0986122886681098
 1.3862943611198906

No entanto, a sintaxe é conveniente.

### Álgebra Linear

([Veja a documentação de álgebra linear](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/))

Julia fornece algumas funcionalidades adicionais relacionadas a operações lineares.

In [107]:
A = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [108]:
det(A)

-2.0

In [109]:
tr(A)

5

In [110]:
eigvals(A)

2-element Array{Float64,1}:
 -0.3722813232690143
  5.372281323269014 

In [111]:
rank(A)

2

## Ranges

Como muitos outros tipos o `Range` pode atuar como um vetor.

In [112]:
a = 10:12        # um intervalo, equivalente a 10: 1: 12 
@show Vector(a)  # pode converter, mas não deve

b = Diagonal([1.0, 2.0, 3.0])
b * a .- [1.0; 2.0; 3.0]

Vector(a) = [10, 11, 12]


3-element Array{Float64,1}:
  9.0
 20.0
 33.0

Também é possível criar intervalos com números de ponto flutuante usando a mesma notação.

In [113]:
a = 0.0:0.1:1.0  # 0.0, 0.1, 0.2, ... 1.0

0.0:0.1:1.0

Mas deve-se tomar cuidado se o nó do terminal não for um múltiplo dos tamanhos definidos.

In [114]:
maxval = 1.0
minval = 0.0
stepsize = 0.15
a = minval:stepsize:maxval # 0.0, 0.15, 0.3, ...
maximum(a) == maxval

false

Para espaçar uniformemente os pontos onde o valor máximo é importante, ou seja, `linspace` em outras linguagens.

In [115]:
maxval = 1.0
minval = 0.0
numpoints = 10
a = range(minval, maxval, length=numpoints)
# ou range(minval, stop=maxval, length=numpoints)

maximum(a) == maxval

true

## Tuples e Tuples Nomeados

([Veja tuples](https://docs.julialang.org/en/v1/manual/functions/#Tuples-1) e [a documentação de tuplas nomeadas](https://docs.julialang.org/en/v1/manual/functions/#Named-Tuples-1))

Nós fomos apresentados a *tuples* anteriormente, que fornecem conjuntos imutáveis de alto desempenho de tipos distintos.

In [116]:
t = (1.0, "test")
t[1]            # acessa pelo índice
a, b = t        # descompacta
# t[1] = 3.0    # falharia, pois as tuplas são imutáveis  
println("a = $a and b = $b")

a = 1.0 and b = test


Bem como **tuplas nomeadas** , que estendem tuplas com nomes para cada argumento.

In [117]:
t = (val1 = 1.0, val2 = "test")
t.val1      # acesso pelo índice 
# a, b = t  # estilo ruim,melhor descompactar pelo nome com o @unpack
println("val1 = $(t.val1) and val1 = $(t.val1)") # acesso pelo nome

val1 = 1.0 and val1 = 1.0


Embora imutável, é possível manipular tuplas e gerar novas.

In [118]:
t2 = (val3 = 4, val4 = "test!!")
t3 = merge(t, t2)  # nova tuple

(val1 = 1.0, val2 = "test", val3 = 4, val4 = "test!!")

As tuplas nomeadas são uma maneira conveniente e de alto desempenho para gerenciar e descompactar conjuntos de parâmetros.

In [119]:
function f(parameters)
    α, β = parameters.α, parameters.β  # estilo pobre, propenso a erros se adicionar parâmetros
    return α + β
end

parameters = (α = 0.1, β = 0.2)
f(parameters)

0.30000000000000004

Essa funcionalidade é auxiliada pelo pacote `Parameters.jl` e pela macro `@unpack`.

In [120]:
using Parameters

function f(parameters)
    @unpack α, β = parameters  # bom estilo, menos sensível a erros
    return α + β
end

parameters = (α = 0.1, β = 0.2)
f(parameters)

0.30000000000000004

Para gerenciar valores padrão, use o macro `@with_kw`.

In [121]:
using Parameters
paramgen = @with_kw (α = 0.1, β = 0.2)  # Cria tuples nomeadas com padrãos

# cria tuplas nomeadas, substituindo os padrões
@show paramgen()  # chamando sem argumentos fornece todos os padrões 
@show paramgen(α = 0.2)
@show paramgen(α = 0.2, β = 0.5);

paramgen() = (α = 0.1, β = 0.2)
paramgen(α=0.2) = (α = 0.2, β = 0.2)
paramgen(α=0.2, β=0.5) = (α = 0.2, β = 0.5)


Uma abordagem alternativa, definindo um novo tipo usando, `struct` tende a ser mais propensa a uso indevido acidental e leva a uma grande quantidade de código padrão.

Por isso, e por outras razões de generalidade, usaremos tuplas nomeadas para coleções de parâmetros sempre que possível.

## Nothing, Missing, e Unions

Às vezes, uma variável, tipo de retorno de uma função ou valor em uma matriz precisa representar a ausência de um valor em vez de um valor específico.

Existem dois casos de uso distintos para isso:

1. `nothing` (“software engineers null”): usado onde nenhum valor faz sentido em um contexto específico devido a uma falha no código, um parâmetro de função não passada, etc.
1. `missing` (“data scientists null”):usado quando um valor faria sentido conceitual, mas não está disponível.



<a id='error-handling'></a>

### Nothing e Tratamento de Erros Básicos

O valor `nothing` é um único valor do tipo `Nothing`

In [122]:
typeof(nothing)

Nothing

Um exemplo de uso razoável de `nothing` é se você precisar ter uma variável definida em um escopo externo, que pode ou não ser definido em um escopo interno.

In [123]:
function f(y)
    x = nothing
    if y > 0.0
        # cálculos para definir `x`
        x = y
    end

    # depois, pode verificar `x` 
    if isnothing(x)
        println("x was not set")
    else
        println("x = $x")
    end
    x
end

@show f(1.0)
@show f(-1.0);

x = 1.0
f(1.0) = 1.0
x was not set
f(-1.0) = nothing


Embora em geral você queira manter um nome de variável vinculado a um único tipo em Julia, essa é uma exceção notável.

Da mesma forma, se necessário, você pode retornar `nothing` de uma função para indicar que ela não foi calculada conforme o esperado.

In [124]:
function f(x)
    if x > 0.0
        return sqrt(x)
    else
        return nothing
    end
end
x1 = 1.0
x2 = -1.0
y1 = f(x1)
y2 = f(x2)

# verifique os resultados com isnothing
if isnothing(y1)
    println("f($x2) successful")
else
    println("f($x2) failed");
end

f(-1.0) failed


Como um aparte, uma maneira equivalente de escrever a função acima é usar o
[operador ternário](https://docs.julialang.org/en/v1/manual/control-flow/index.html#man-conditional-evaluation-1),
 que fornece uma estrutura compacta if/then/else.

In [125]:
function f(x)
    x > 0.0 ? sqrt(x) : nothing  # o padrão "a? b: c" é o ternário
end

f(1.0)

1.0

Às vezes, usaremos este formulário quando tornar o código mais claro (e ocasionalmente aumentará o desempenho do código).

Independentemente de como `f(x)` está escrito, o tipo de retorno é um exemplo de união, onde o resultado pode ser um de um conjunto explícito de tipos.

Nesse caso específico, o compilador deduziria que o tipo seria um `Union{Nothing,Float64}`- ou seja, ele retornará um ponto flutuante ou um `nothing`.

Você verá esse tipo diretamente se usar uma matriz que contenha os dois tipos.

In [126]:
x = [1.0, nothing]

2-element Array{Union{Nothing, Float64},1}:
 1.0     
  nothing

Ao considerar o tratamento de erros, se você deseja que uma função retorne `nothing` ou simplesmente falhe, depende se a chamada de código `f(x)` está verificando cuidadosamente os resultados.

Por exemplo, se você estava chamando uma matriz de parâmetros em que a priori não tinha certeza de quais serão bem-sucedidos, então:

In [127]:
x = [0.1, -1.0, 2.0, -2.0]
y = f.(x)

# presumivelmente verifique `y`

4-element Array{Union{Nothing, Float64},1}:
 0.31622776601683794
  nothing           
 1.4142135623730951 
  nothing           

Por outro lado, se o parâmetro passado for inválido e você preferir não lidar com uma falha normal, usar uma asserção será mais apropriado.

In [128]:
function f(x)
    @assert x > 0.0
    sqrt(x)
end

f(1.0)

1.0

Por fim, `nothing` é uma boa maneira de indicar um parâmetro opcional em uma função.

In [129]:
function f(x; z = nothing)

    if isnothing(z)
        println("No z given with $x")
    else
        println("z = $z given with $x")
    end
end

f(1.0)
f(1.0, z=3.0)

No z given with 1.0
z = 3.0 given with 1.0


Uma alternativa para `nothing`, que pode ser útil e, às vezes, com desempenho mais alto, é usar `NaN` para sinalizar que um valor é inválido ao retornar de uma função.

In [130]:
function f(x)
    if x > 0.0
        return x
    else
        return NaN
    end
end

f(0.1)
f(-1.0)

@show typeof(f(-1.0))
@show f(-1.0) == NaN  # nota, isso falha!
@show isnan(f(-1.0))  # verifique isso

typeof(f(-1.0)) = Float64
f(-1.0) == NaN = false
isnan(f(-1.0)) = true


true

Observe que, nesse caso, o tipo de retorno é `Float64` independente da entrada para o input `Float64`.

Lembre-se, porém, de que isso só funciona se o tipo de retorno de uma função for `Float64`.

### Exceções

(veja [a documentação de excessões](https://docs.julialang.org/en/v1/manual/control-flow/index.html#Exception-Handling-1))

Embora retornar um `nothing` possa ser uma boa maneira de lidar com funções que podem ou não retornar valores, um método mais robusto de tratamento de erros é usar exceções.

A menos que você esteja escrevendo um pacote, raramente desejará definir e lançar suas próprias exceções, mas precisará lidar com eles de outras bibliotecas.

A distinção de chave para quando usar uma exceção *vs.* o retorno `nothing` é se um erro é inesperado em vez de um caminho normal de execução.

Um exemplo de exceção é a `DomainError`, que significa que um valor passado para uma função é inválido.

In [131]:
# lança exceção, desativada para impedir a quebra de bloco de anotações 
# sqrt(-1.0)

# para ver o erro
try sqrt(-1.0); catch err; err end  # captura a exceção e a printa

DomainError(-1.0, "sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).")

Outro exemplo que você verá é quando o compilador não pode converter entre tipos.

In [132]:
# lança exceção, desativada para evitar a quebra de bloco de anotações 
# converte (Int64, 3.12)

# para ver o erro
try convert(Int64, 3.12); catch err; err end  # captura a excessão e a printa

InexactError(:Int64, Int64, 3.12)

Se essas exceções forem geradas a partir de casos inesperados no seu código, pode ser apropriado simplesmente permitir que elas ocorram e garantir que você possa ler o erro.

Ocasionalmente, você deseja capturar esses erros e tentar recuperar, como fizemos acima no bloco `try`.

In [133]:
function f(x)
    try
        sqrt(x)
    catch err                # entra se a exceção é lançada 
        sqrt(complex(x, 0))  # converte para número complexo 
    end
end

f(0.0)
f(-1.0)

0.0 + 1.0im


<a id='missing'></a>

### Missing

(Veja a [ documentação de "missing"](https://docs.julialang.org/en/v1/manual/missing/))

O valor `missing` do tipo `Missing`é usado para representar o valor ausente em sentido estatístico.

Por exemplo, se você carregou dados de um painel e existiam lacunas.


In [134]:
x = [3.0, missing, 5.0, missing, missing]

5-element Array{Union{Missing, Float64},1}:
 3.0     
  missing
 5.0     
  missing
  missing

Uma característica fundamental do `missing` é que ela se propaga através de outras chamadas de função - ao contrário do `nothing`

In [135]:
f(x) = x^2

@show missing + 1.0
@show missing * 2
@show missing * "test"
@show f(missing);      # até funções definidas pelo usuário 
@show mean(x);

missing + 1.0 = missing
missing * 2 = missing
missing * "test" = missing
f(missing) = missing
mean(x) = missing


O objetivo disso é garantir que as falhas não falhem silenciosamente e fornecer resultados numéricos sem sentido.

Isso também se aplica à comparação de valores, que:

In [136]:
x = missing

@show x == missing
@show x === missing  # um exceção
@show ismissing(x);

x == missing = missing
x === missing = true
ismissing(x) = true


Onde `ismissing` é a maneira canônica de testar o valor.

No caso em que você deseja calcular um valor sem os valores ausentes, você pode usar `skipmissing`.

In [137]:
x = [1.0, missing, 2.0, missing, missing, 5.0]

@show mean(x)
@show mean(skipmissing(x))
@show coalesce.(x, 0.0);  # substitui missing com 0.0;

mean(x) = missing
mean(skipmissing(x)) = 2.6666666666666665
coalesce.(x, 0.0) = [1.0, 0.0, 2.0, 0.0, 0.0, 5.0]


Como `missing` é semelhante ao tipo R `NA`, veremos mais `missing` quando abordamos`DataFrames`

## Exercícios


<a id='np-ex1'></a>

### Exercício 1

Este exercício utiliza operações matriciais que surgem em certos problemas, inclusive ao lidar com equações de diferença estocástica linear.

Se você não estiver familiarizado com toda a terminologia, não se preocupe - você pode ler a discussão de fundo e se concentrar apenas no exercício da matriz.

Com isso dito, considere a equação da diferença estocástica:


<a id='equation-ja-sde'></a>
$$
X_{t+1} = A X_t + b + \Sigma W_{t+1} \tag{1}
$$

Onde

- $ X_t, b $ e $ X_{t+1} $ são $ n \times 1 $  
- $ A $ é $ n \times n $  
- $ \Sigma $ é $ n \times k $  
- $ W_t $ é $ k \times 1 $ é $ \{W_t\} $ é iid com média zero e matriz de variância-covariância igual à matriz de identidade.


faça $ S_t $ denotar $ n \times n $ a matriz de variância e covariância de $ X_t $

Usando as regras para calcular variações em expressões matriciais, pode ser mostrado em [(1)](#equation-ja-sde) que $ \{S_t\} $ obedece


<a id='equation-ja-sde-v'></a>
$$
S_{t+1} = A S_t A' + \Sigma \Sigma' \tag{2}
$$

Pode-se demonstrar que, desde que todos os autovalores de  $ A $ dentro do círculo unitário, a sequência $ \{S_t\} $ convege para um limite único $ S $

Esta é a **variação incondicional** ou **variação assintótica** da equação da diferença estocástica.

Como exercício, tente escrever uma função simples que resolva para o limite $ S $ iterado em [(2)](#equation-ja-sde-v) dado $ A $ e $ \Sigma $

Para testar sua solução, observe que o limite $ S $ é uma solução para a equação da matriz:


<a id='equation-ja-dle'></a>
$$
S = A S A' + Q
\quad \text{onde} \quad Q := \Sigma \Sigma' \tag{3}
$$

Esse tipo de equação é conhecida como **equação de Lyapunov de tempo discreto**.

O [pacote QuantEcon ](http://quantecon.org/julia_index.html)
fornece uma função chamada `solve_discrete_lyapunov` que implementa um rápido algoritmo de "duplicação" para resolver essa equação.

Teste seu método iterativo em relação ao `solve_discrete_lyapunov` usando matrizes:

$$
A =
\begin{bmatrix}
    0.8 & -0.2  \\
    -0.1 & 0.7
\end{bmatrix}
\qquad
\Sigma =
\begin{bmatrix}
    0.5 & 0.4 \\
    0.4 & 0.6
\end{bmatrix}
$$

### Exercício 2

Faça um processo estocástico para $ \{y_t\}_{t=0}^T $

$$
y_{t+1} = \gamma + \theta y_t + \sigma w_{t+1}
$$

onde

- $ w_{t+1} $ é $\sim $ N **(0,1)**

- $ \gamma=1, \sigma=1, y_0 = 0 $  
- $ \theta \in \Theta \equiv \{0.8, 0.9, 0.98\} $  


Dados esses parâmetros

- simule uma única $ y_t $ série para cada $ \theta \in \Theta $
  para $ T = 150 $.  Sinta-se livre para experimentar diferentes $ T $  
- Gráficos de sobreposição da média móvel do processo para cada $ \theta \in \Theta $,
   ou seja, para cada  $ 1 \leq \tau \leq T $ plote:


$$
\frac{1}{\tau}\sum_{t=1}^{\tau}y_T
$$

- Simule $ N=200 $ formas do processo estocástico acima para o $ T $,
  para cada $ \theta \in \Theta $, onde nos referimos a um elemento de uma simulação específica como $ y^n_t $  
  
- Overlay plota um histograma da distribuição estacionária do  $ y^n_T $ para cada $ \theta \in \Theta $.  Dica: passe`alpha`.
  para um gráfico e torná-lo transparente (ou seja `histogram(vals, alpha = 0.5)`) ou
  use `stephist(vals)` para mostrar apenas a função de etapa do histograma.
- Encontre numericamente a média e a variância disso como uma média de conjunto, ou seja
  $ \sum_{n=1}^N\frac{y^n_T}{N} $ e
  $ \sum_{n=1}^N\frac{(y_T^n)^2}{N} -\left(\sum_{n=1}^N\frac{y^n_T}{N}\right)^2 $  


Mais tarde, interpretaremos alguns deles [nesta aula](https://lectures.quantecon.org/tools_and_techniques/lln_clt.html)

### Exercício 3

Deixe o processo de geração de dados para uma variável ser:

$$
y = a x_1 + b x_1^2 + c x_2 + d + \sigma w
$$

onde $ y, x_1, x_2 $ são variaveis escalares observáveis, $ a,b,c,d $ são parâmetros para serem estimados, e $ w $ é normal *iid* com média 0 e variância 1.

Primeiro, vamos simular os dados para estimar os parâmetros:

- Faça $ N=50 $ valores para $ x_1, x_2 $ de distribuições normais *iid* 


Então, simule com $ w $ diferentes
* Faça um vetor $ w $ para `N` valores e então `y` para isso simule dados se os parâmentros forem $ a = 0.1, b = 0.2 c = 0.5, d = 1.0, \sigma = 0.1 $
* Repita então aquilo que você tem  `M = 20` diferentes simulações de `y`  para `N` valores

Finalmente, calcule a ordem dos mínimos quadrados ordinários manualmente (por exemplo,  coloque os observáveis ​​em matrizes e vetores e use diretamente as equações para
[MQO](https://en.wikipedia.org/wiki/Ordinary_least_squares) em vez de um pacote)

- Para cada uma das simulações `M=20`, calcule as estimativas de MQO $ a, b, c, d, \sigma $  
- Plote um histograma dessas variações para cada variável 

### Exercício 4

Refaça o exercício 1 usando a função `fixedpoint` disbonível em `NLsolve` [nessa aula](https://julia.quantecon.org/julia_by_example.html).

Compare o número de iterações da Anderson Acceleration do NLsolve com a iteração codificada à mão usada no Exercício 1.

Dica: converta a matriz em um vetor para usar `fixedpoint`. ou seja. `A = [1 2; 3 4]` então `x = reshape(A, 4)` transforma em um vetor. Reverter, `reshape(x, 2, 2)`.

## Soluções

### Exercício 1

Aqui está uma abordagem iterativa:

In [138]:
function compute_asymptotic_var(A, Σ;
                                S0 = Σ * Σ',
                                tolerance = 1e-6,
                                maxiter = 500)
    V = Σ * Σ'
    S = S0
    err = tolerance + 1
    i = 1
    while err > tolerance && i ≤ maxiter
        next_S = A * S * A' + V
        err = norm(S - next_S)
        S = next_S
        i += 1
    end
    return S
end

compute_asymptotic_var (generic function with 1 method)

In [139]:
A = [0.8  -0.2;
     -0.1  0.7]

Σ = [0.5 0.4;
     0.4 0.6]

2×2 Array{Float64,2}:
 0.5  0.4
 0.4  0.6

Note que todos os autovalores de $ A $ encontram-se dentro do disco da unidade.

In [140]:
maximum(abs, eigvals(A))

0.9

Vamos computar a variância assintótica.

In [141]:
our_solution = compute_asymptotic_var(A, Σ)

2×2 Array{Float64,2}:
 0.671228  0.633476
 0.633476  0.858874

Agora vamos fazer a mesma coisa usando a função `solve_discrete_lyapunov ()` do QuantEcon e verificar se obtemos o mesmo resultado:

In [142]:
using QuantEcon

In [143]:
norm(our_solution - solve_discrete_lyapunov(A, Σ * Σ'))

3.883245447999784e-6